import AppKit

// MARK: - ClipboardMonitor
// Remembers the last few pieces of text you copied so they can be copied again from the notch.
// History lives in memory only (gone when Coucou quits) and anything a password manager marks
// as concealed or transient is never recorded.

@MainActor
final class ClipboardMonitor {
    static let shared = ClipboardMonitor()
    static let capacity = 12

    private var timer: Timer?
    private var lastChange = NSPasteboard.general.changeCount
    private var app: AppState { AppState.shared }

    private static let skippedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
    ]

    private init() {}

    func start() {
        guard timer == nil else { return }
        // The pasteboard has no change notification; comparing one integer a second costs nothing.
        let t = Timer(timeInterval: 1, repeats: true) { _ in
            Task { @MainActor in ClipboardMonitor.shared.check() }
        }
        t.tolerance = 0.4
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    private func check() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChange else { return }
        lastChange = pb.changeCount
        guard app.activeIntegrations.contains("integration_clipboard") else { return }

        let types = Set((pb.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.skippedTypes),
              let text = pb.string(forType: .string) else { return }
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, text.count <= 20_000 else { return }

        var clips = app.clips
        clips.removeAll { $0.text == text }
        clips.insert(ClipItem(text: text, date: Date()), at: 0)
        app.clips = Array(clips.prefix(Self.capacity))
        NotificationCenter.default.post(name: .botReact, object: BotReaction.catchIt)   // Mochi catches it
    }

    /// Puts an earlier item back on the clipboard and moves it to the top.
    func copy(_ item: ClipItem) {
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(item.text, forType: .string)
        lastChange = pb.changeCount
        var clips = app.clips
        clips.removeAll { $0.id == item.id }
        clips.insert(item, at: 0)
        app.clips = clips
        SoundEngine.shared.play("pop")
    }

    func clear() { app.clips = [] }
}
